name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files to AWS Lightsail instance
        run: |
          chmod 600 ${{ secrets.LIGHTSAIL_KEY }}
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.LIGHTSAIL_KEY }} bitnami@${{ secrets.LIGHTSAIL_IP }} "sudo rm -rf ${LIGHTSAIL_ROOT_DIR}/*"
          scp -o StrictHostKeyChecking=no -i ${{ secrets.LIGHTSAIL_KEY }} -r * bitnami@${{ secrets.LIGHTSAIL_IP }}:${{ secrets.LIGHTSAIL_ROOT_DIR }}

      - name: Run Composer and NPM commands on Lightsail instance
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.LIGHTSAIL_KEY }} bitnami@${{ secrets.LIGHTSAIL_IP }} "
            cd ${LIGHTSAIL_ROOT_DIR} &&
            composer update &&
            npm install &&
            npm run build
          "

      - name: Restart Nginx on AWS Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.LIGHTSAIL_KEY }} bitnami@${{ secrets.LIGHTSAIL_IP }} "sudo /opt/bitnami/ctlscript.sh restart nginx"
      
      - name: Deployment completed Successfully
        run: echo "Deployment completed successfuly"
