name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH for AWS Lightsail
        run: |
          echo "${{ secrets.LIGHTSAIL_KEY }}" > lightsail_key.pem
          chmod 600 lightsail_key.pem

      - name: Clone repository if not exists or pull changes
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem bitnami@${{ secrets.LIGHTSAIL_IP }} "
            if [ ! -d /opt/bitnami/nginx/html/.git ]; then
              # If .git doesn't exist, clone the repository
              cd /opt/bitnami/nginx/html &&
              git clone https://github.com/TekRajBhattaa/carepoint-deployment.git
            else
              # If .git exists, pull the latest changes
              cd /opt/bitnami/nginx/html &&
              git pull origin main
            fi
          "

      - name: Run Composer and NPM commands on Lightsail instance
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem bitnami@${{ secrets.LIGHTSAIL_IP }} "
            # Explicitly remove any incorrect NVM setup and install fresh
            unset NVM_DIR
            export NVM_DIR=\"$HOME/.nvm\"
            rm -rf \$NVM_DIR  # Delete any existing NVM installation to ensure a clean slate

            # Install NVM and ensure the proper version of Node.js is used
            echo 'Installing NVM...'
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

            # Load NVM in the current shell session
            . \$NVM_DIR/nvm.sh

            # Install and use the latest LTS version of Node.js
            nvm install --lts
            nvm use --lts

            # Verify installation of Node.js and NPM
            node -v
            npm -v

            # Navigate to project directory and run Composer and NPM commands
            cd /opt/bitnami/nginx/html/carepoint-deployment
            composer update
            npm install
            npm run build
          "

      - name: Restart Nginx on AWS Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem bitnami@${{ secrets.LIGHTSAIL_IP }} "sudo /opt/bitnami/ctlscript.sh restart nginx"

      - name: Deployment completed Successfully
        run: echo "Deployment completed successfully"
