name: Deploy to WP Engine

on:
  push:
    branches:
      - development
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install Composer dependencies
      - name: Install Composer Dependencies
        run: composer update
      
      # Install NPM dependencies
      - name: Install NPM Dependencies
        run: npm install

      # Build Frontend Assets
      - name: Build Frontend Assets
        run: npm run build

      # Deploy to WP Engine (Development)
      - name: Deploy to WP Engine (Dev)
        if: github.ref == 'refs/heads/development'
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: 'Dev'
          CACHE_CLEAR: TRUE

      # Deploy to WP Engine (Staging)
      - name: Deploy to WP Engine (Staging)
        if: github.ref == 'refs/heads/staging'
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: 'Stg'
          CACHE_CLEAR: TRUE

      # Deploy to WP Engine (Production)
      - name: Deploy to WP Engine (Production)
        if: github.ref == 'refs/heads/main'
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: 'Prd'
          CACHE_CLEAR: TRUE
          
