name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH for AWS Lightsail
        run: |
          echo "${{ secrets.LIGHTSAIL_KEY }}" > lightsail_key.pem
          chmod 600 lightsail_key.pem

      - name: Clone repository if not exists or pull changes
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem bitnami@${{ secrets.LIGHTSAIL_IP }} "
            if [ ! -d /opt/bitnami/nginx/html/.git ]; then
              # If .git doesn't exist, clone the repository
              cd /opt/bitnami/nginx/html &&
              git clone https://github.com/TekRajBhattaa/carepoint-deployment.git
            else
              # If .git exists, pull the latest changes
              cd /opt/bitnami/nginx/html &&
              git pull origin main
            fi
          "

      - name: Run Composer and NPM commands on Lightsail instance
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem bitnami@${{ secrets.LIGHTSAIL_IP }} "
            # Load NVM or install NVM if not available
            if [ -s \"$HOME/.nvm/nvm.sh\" ]; then
              echo 'NVM is already installed';
              source $HOME/.nvm/nvm.sh;
            else
              echo 'Installing NVM';
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash;
              export NVM_DIR=\"$HOME/.nvm\"
              source $NVM_DIR/nvm.sh;
              nvm install node;
            fi

            # Use the correct Node version
            nvm use node;

            # Check if NPM is installed
            if command -v npm >/dev/null 2>&1; then
              echo 'NPM is installed';
            else
              echo 'NPM is not installed, installing it now';
              nvm install --latest-npm;
            fi

            # Run the required commands
            cd /opt/bitnami/nginx/html/carepoint-deployment &&
            composer update &&
            npm install &&
            npm run build
          "

      - name: Restart Nginx on AWS Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem bitnami@${{ secrets.LIGHTSAIL_IP }} "sudo /opt/bitnami/ctlscript.sh restart nginx"

      - name: Deployment completed Successfully
        run: echo "Deployment completed successfully"
