name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH for AWS Lightsail
        run: |
          echo "${{ secrets.LIGHTSAIL_KEY }}" > lightsail_key.pem
          chmod 600 lightsail_key.pem

      - name: Clone repository if not exists or pull changes
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem bitnami@${{ secrets.LIGHTSAIL_IP }} "
            if [ ! -d /opt/bitnami/nginx/html/.git ]; then
              # If .git doesn't exist, clone the repository
              cd /opt/bitnami/nginx/html &&
              git clone https://github.com/TekRajBhattaa/carepoint-deployment.git
            else
              # If .git exists, pull the latest changes
              cd /opt/bitnami/nginx/html &&
              git pull origin main
            fi
          "

      - name: Run Composer and NPM commands on Lightsail instance
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem bitnami@${{ secrets.LIGHTSAIL_IP }} "
            # Explicitly load NVM if installed, or install it
            export NVM_DIR=\"$HOME/.nvm\"
            if [ -s \"$NVM_DIR/nvm.sh\" ]; then
              echo 'NVM is already installed';
              . \"$NVM_DIR/nvm.sh\"  # This loads nvm
            else
              echo 'Installing NVM';
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash;
              . \"$HOME/.nvm/nvm.sh\"  # Load newly installed NVM
            fi

            # Install and use the latest LTS version of Node.js
            nvm install --lts
            nvm use --lts

            # Verify Node.js and NPM installation
            node -v
            npm -v

            # Navigate to project directory and run Composer and NPM commands
            cd /opt/bitnami/nginx/html/carepoint-deployment
            composer update
            npm install
            npm run build
          "

      - name: Restart Nginx on AWS Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem bitnami@${{ secrets.LIGHTSAIL_IP }} "sudo /opt/bitnami/ctlscript.sh restart nginx"

      - name: Deployment completed Successfully
        run: echo "Deployment completed successfully"
