name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main  # Deploy when the main branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}  # Your .pem file added to GitHub Secrets
        key_name: id_rsa
        known_hosts: |
          3.224.100.210  # Lightsail static IP

    - name: Sync files to AWS Lightsail
      run: |
        rsync -avz --delete ./ bitnami@3.224.100.210:/opt/bitnami/nginx/html/

    - name: Run build commands on Lightsail
      run: |
        ssh -o StrictHostKeyChecking=no bitnami@3.224.100.210 << 'EOF'
        cd /opt/bitnami/nginx/html/
        composer update
        npm install
        npm run build
        EOF
