name: Deploy to WP Engine

on:
  push:
    branches:
      - development
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install Composer dependencies
      - name: Install Composer Dependencies
        run: composer update
      
      # Install NPM dependencies
      - name: Install NPM Dependencies
        run: npm install

      # Build Frontend Assets
      - name: Build Frontend Assets
        run: npm run build

      # Deploy Bedrock's wp-config.php file to the correct location
      - name: Deploy wp-config.php from SRC_PATH to REMOTE_PATH
        run: |
          rsync -az -e "ssh -o StrictHostKeyChecking=no -i ${{ secrets.WPE_SSHG_KEY_PRIVATE }}" \
          web/wp-config.php \
          ${{ secrets.WPE_USER }}@${{ secrets.WPE_HOST }}:/sites/${{ secrets.WPE_ENV }}/web/wp-config.php

      # Deploy to WP Engine (Development)
      - name: Deploy to WP Engine (Dev)
        if: github.ref == 'refs/heads/development'
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: 'Dev'
          CACHE_CLEAR: TRUE

      # Deploy to WP Engine (Staging)
      - name: Deploy to WP Engine (Staging)
        if: github.ref == 'refs/heads/staging'
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: 'Stg'
          CACHE_CLEAR: TRUE

      # Deploy to WP Engine (Production)
      - name: Deploy to WP Engine (Production)
        if: github.ref == 'refs/heads/main'
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: 'cpnewdev'
          CACHE_CLEAR: TRUE
          
